### ISSUE TITLE
Local Data Collection

### ISSUE THREAD

**Issue by asorici** [ami-lab/google-awareness-upb#4]
## Why
In order to analyze the data collected via Google Awareness API, we want to assess its quality, as well as the impact on phone performance (battery consumption, CPU usage, etc). Therefore, an initial local data collection service and storage is implemented as an Android Service.

## What
  * [x] interface to enable/disable the Google Awareness API data collection service
  * [ ] interface to configure the data collection frequency and status of the service
  * [ ] Run the service daily for a week and collect data into a locally stored CSV file
  * [ ] Data cleanup (missing values, outliers) and analysis (e.g. max, min, avg aggregations, graphs)

## Notes
